FROM debian:bookworm 

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \ 
    wget \
    php \
    php-fpm \
    php-mysql \
    netcat-openbsd && \ 
    update-ca-certificates && \
    wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /bin/wp && \ 
    mkdir -p /var/www/html/ && \
    chown -R www-data:www-data /var/www/html/ && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

COPY ./conf/www.conf /etc/php/8.2/fpm/pool.d/
COPY ./tools/configure.sh /bin/
RUN chmod +x /bin/configure.sh

ENTRYPOINT ["/usr/sbin/php-fpm8.2"]
CMD ["-F"]
